version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: async-rickandmorty-web
    volumes:
      - ".:/app"
    tty: true