apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-06T03:32:49Z"
  generation: 1
  labels:
    app: async-rickandmorty-web
  name: async-rickandmorty-web
  namespace: default
  resourceVersion: "38553"
  selfLink: /apis/apps/v1/namespaces/default/deployments/async-rickandmorty-web
  uid: ee4a0534-9086-42ca-a672-efd7af0c3c5b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: async-rickandmorty-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: async-rickandmorty-web
    spec:
      containers:
      - image: caprilespe/async-rickandmorty-web:v1
        imagePullPolicy: IfNotPresent
        name: async-rickandmorty-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-09-06T03:32:49Z"
    lastUpdateTime: "2021-09-06T03:33:17Z"
    message: ReplicaSet "async-rickandmorty-web-5d97c4d47f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-09-06T03:33:59Z"
    lastUpdateTime: "2021-09-06T03:33:59Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
